<?php
require_once __DIR__ . '/ProjectConfiguration.php';

/** One should build a model for each table in the database, as it enables extra operations */
abstract class Model {
    // Provided by the class that extends this. Trust their values and assume they are constant
    public static array $fillable; // Attributes that can be provided by constructing the value manually (except id)
    public static string $sql_table; // SQL table that holds the data
    public static string $representative; // Column that contains a short description of the element. It may not be unique. It must be in $fillable
    public static string $id_column; // Column that contains the id. Must be a primary key, composite primary keys are not supported
    public static array $pointers; // Foreign key -> Model::class mapping
    /// ---

    public array $data = [];

    public function __construct(array $data) {
        $columns = array_merge([static::$id_column], static::$fillable);

        // Default value to avoid undefined key errors on valid column names
        $this->data = array_fill_keys($columns, null);

        foreach ($columns as $col) {
            $this->data[$col] = $data[$col] ?? null;
        }

        $this->onConstruct();
    }
    /** Called upon constructing the model. A bit less error-prone than overriding the constructor */
    public abstract function onConstruct(): void;

    /** Retrieve the id of the current model */
    public function id(): null|int {
        return $this->data[static::$id_column];
    }

    /** Load models from entries on array. Note that every property in $fillable must be present (and optionally, also the $id_column) */
    public static function fromArray(array $all): array {
        $store = [];
        foreach ($all as $key => $data) {
            $store[$key] = new static($data);
        }
        return $store;
    }

    /** Load models from entries generated by a query, the latter is generated via a function that is passed the columns and the table */
    public static function fromQuery($query_fn, array $subst): array {
        $columns = implode(', ', array_merge([static::$id_column], static::$fillable));
        return self::fromArray(
            Services::with('db')->statement($query_fn($columns, static::$sql_table), $subst),
        );
    }

    /** Load models from entries generated by a query, the latter is generated via a function that is passed the columns and the table. Note that the query must return one value */
    public static function fromQueryOne($query_fn, array $subst): static | null {
        $columns = implode(', ', array_merge([static::$id_column], static::$fillable));
        $data = Services::with('db')->statement($query_fn($columns, static::$sql_table), $subst);

        if (count($data) !== 1) {
            return null;
        }
        return new static($data[0]);
    }

    /** Return every value from the table as an array of models */
    public static function all(): array {
        return self::fromQuery(
            fn($col, $tbl) => "SELECT {$col} FROM `{$tbl}`",
            []
        );
    }

    /** ID - Representative mapping to build UIs on tables using foreign keys */
    public static function representatives(): array {
        $data = Services::with('db')->statement(
            'SELECT ' . static::$id_column . ' as id, ' . static::$representative . ' as repr FROM ' . static::$sql_table,
            []
        );
        $result = [];
        foreach ($data as $datum) {
            $result[$datum['id']] = $datum['repr'];
        }
        return $result;
    }

    /** Extract one model by id from the database */
    public static function find(mixed $id): static | null {
        return self::fromQueryOne(
            fn($col, $tbl) => "SELECT {$col} FROM `{$tbl}` WHERE ".static::$id_column.' = :id',
            ['id' => $id]
        );
    }

    /** Get the model associated to the current one by following a pointer / foreign key */
    public function pointer(string $foreign_key_column): object | null {
        return (static::$pointers[$foreign_key_column])::find(
            $this->data[$foreign_key_column]
        );
    }

    public static function save(array $instances): void {
        $to_insert = array_filter($instances, fn($inst) => is_null($inst->id()));
        $to_replace = array_filter($instances, fn($inst) => !is_null($inst->id()));

        $insert_columns = static::$fillable;
        $replace_columns = array_merge([static::$id_column], static::$fillable);

        $insert_built = self::buildPlaceholders($to_insert, $insert_columns);
        $replace_built = self::buildPlaceholders($to_replace, $replace_columns);

        if (count($insert_built['fills']) > 0) {
            Services::with('db')->statement(
                'INSERT INTO `' . static::$sql_table. "` ({$insert_built['columns']}) VALUES {$insert_built['placeholders']}",
                $insert_built['fills']
            );
        }
        if (count($replace_built['fills']) > 0) {
            Services::with('db')->statement(
                'REPLACE INTO `' . static::$sql_table . "` ({$replace_built['columns']}) VALUES {$replace_built['placeholders']}",
                $replace_built['fills']
            );
        }
    }

    public static function deleteOne(mixed $id): void {
        Services::with('db')->statement(
            'DELETE FROM ' . static::$sql_table . ' WHERE ' . static::$id_column . ' = :id',
            ['id' => $id]
        );
    }

    private static function buildPlaceholders(array $instances, array $columns): array {
        $sql_columns = implode(', ', $columns);
        $column_placeholder = '(' . implode(', ', array_fill(0, count($columns), '?')) . ')';
        $placeholders = implode(', ', array_fill(0, count($instances), $column_placeholder));
        $fills = array_merge(...array_map(fn(object $inst) => array_map(fn ($col) => $inst->data[$col], $columns), $instances));
        return [
            'placeholders' => $placeholders,
            'fills' => $fills,
            'columns' => $sql_columns,
        ];
    }
}

?>
